# -*- coding: utf-8 -*-
"""Pickle code for simple linear regression

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1no0nFKHoTISc-RfLfSFDQrGizEsOSTAZ
"""

import streamlit as st
import pandas as pd
import joblib

# Title and description
st.title("🏦 Simple Linear Regression - Loan Amount Predictor")
st.write("Upload your trained **pickle (.pkl)** file to make predictions based on income.")

# Step 1: Upload the Pickle File
uploaded_model = st.file_uploader("Upload your Pickle Model File", type=["pkl"])

# Step 2: Load the model once uploaded
if uploaded_model is not None:
    try:
        model = joblib.load(uploaded_model)
        st.success("✅ Model loaded successfully!")

        # Step 3: Input for prediction
        st.subheader("Enter Input Data for Prediction")
        income = st.number_input("Enter Annual Income (in ₹)", min_value=0.0, step=1000.0)

        # Step 4: Make Prediction
        if st.button("Predict Loan Amount"):
            try:
                # As per your regression model (with statsmodels)
                X_new = pd.DataFrame({'const': [1], ' income_annum': [income]})
                prediction = model.predict(X_new)
                st.success(f"💰 Predicted Loan Amount: ₹{prediction[0]:,.2f}")
            except Exception as e:
                st.error(f"⚠️ Error during prediction: {e}")

    except Exception as e:
        st.error(f"❌ Failed to load model file. Error: {e}")

else:
    st.info("👆 Please upload your model file (.pkl) to continue.")