# -*- coding: utf-8 -*-
"""Pickle code for simple linear regression

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1no0nFKHoTISc-RfLfSFDQrGizEsOSTAZ
"""

import streamlit as st
import pandas as pd
import joblib

st.title("📈 Loan Amount Prediction App")
st.write("Upload your trained model (.pkl) and input data to predict loan amount.")

# Upload the trained pickle/model file
uploaded_model = st.file_uploader("Upload Pickle Model File", type=["pkl"])

if uploaded_model is not None:
    # Load the model
    model = joblib.load(uploaded_model)
    st.success("✅ Model loaded successfully!")

    st.subheader("Enter Input Data")
    income = st.number_input("Enter Annual Income", min_value=0.0, step=1000.0)

    if st.button("Predict Loan Amount"):
        try:
            # Create DataFrame with constant (as model expects sm.add_constant)
            X_new = pd.DataFrame({'const': [1], ' income_annum': [income]})

            # Predict using the loaded model
            prediction = model.predict(X_new)
            st.success(f"💰 Estimated Loan Amount: {prediction[0]:,.2f}")
        except Exception as e:
            st.error(f"Error during prediction: {e}")

else:
    st.info("Please upload your model file (.pkl) to begin.")